# --- LANGUAGE MAPPING ---
LANGUAGE_MAP = {
    "aar": "Afar",
    "abk": "Abcaso",
    "ace": "Acinese",
    "ach": "Acoli",
    "ada": "Adangme",
    "ady": "Adighè",
    "afa": "Afroasiatiche (Altre)",
    "afh": "Afrihili (Lingua artificiale)",
    "afr": "Afrikaans",
    "ain": "Ainu",
    "aka": "Akan",
    "akk": "Accadico",
    "alb": "Albanese",
    "ale": "Aleutino",
    "alg": "Algonchine (Altre)",
    "alt": "Altaico",
    "amh": "Amarico",
    "ang": "Inglese antico (ca. 450-1100)",
    "anp": "Angika",
    "apa": "Lingue Apache",
    "ara": "Arabo",
    "arc": "Aramaico",
    "arg": "Aragonese",
    "arm": "Armeno",
    "arn": "Mapuche",
    "arp": "Arapaho",
    "art": "Artificiali (Altre)",
    "arw": "Arawak",
    "asm": "Assamese",
    "ast": "Asturiano (Bable)",
    "ath": "Athabaska (Altre)",
    "aus": "Lingue australiane",
    "ava": "Avaro",
    "ave": "Avestico",
    "awa": "Awadhi",
    "aym": "Aymara",
    "aze": "Azero",
    "bad": "Lingue banda",
    "bai": "Lingue bamileke",
    "bak": "Baschiro",
    "bal": "Beluci",
    "bam": "Bambara",
    "ban": "Balinese",
    "baq": "Basco",
    "bas": "Basa",
    "bat": "Baltiche (Altre)",
    "bej": "Begia",
    "bel": "Bielorusso",
    "bem": "Bemba",
    "ben": "Bengalese",
    "ber": "Berbere (Altre)",
    "bho": "Bhojpuri",
    "bih": "Bihari (Altre)",
    "bik": "Bikol",
    "bin": "Edo",
    "bis": "Bislama",
    "bla": "Siksika",
    "bnt": "Bantu (Altre)",
    "bos": "Bosniaco",
    "bra": "Braj",
    "bre": "Bretone",
    "btk": "Batak",
    "bua": "Buriato",
    "bug": "Buginese",
    "bul": "Bulgaro",
    "bur": "Birmano",
    "byn": "Bilin",
    "cad": "Caddo",
    "cai": "Indiane centroamericane (Altre)",
    "car": "Caribico",
    "cat": "Catalano",
    "cau": "Caucasiche (Altre)",
    "ceb": "Cebuano",
    "cel": "Celtiche (Altre)",
    "cha": "Chamorro",
    "chb": "Chibcha",
    "che": "Ceceno",
    "chg": "Chagatai",
    "chi": "Cinese",
    "chk": "Chuukese",
    "chm": "Mari",
    "chn": "Gergo Chinook",
    "cho": "Choctaw",
    "chp": "Chipewyan",
    "chr": "Cherokee",
    "chu": "Slavo ecclesiastico",
    "chv": "Ciuvascio",
    "chy": "Cheyenne",
    "cmc": "Lingue chamic",
    "cnr": "Montenegrino",
    "cop": "Copto",
    "cor": "Cornico",
    "cos": "Corso",
    "cpe": "Creoli e Pidgin, basati sull'inglese (Altri)",
    "cpf": "Creoli e Pidgin, basati sul francese (Altri)",
    "cpp": "Creoli e Pidgin, basati sul portoghese (Altri)",
    "cre": "Cree",
    "crh": "Tataro di Crimea",
    "crp": "Creoli e Pidgin (Altri)",
    "csb": "Casciubo",
    "cus": "Cuscitiche (Altre)",
    "cze": "Ceco",
    "dak": "Dakota",
    "dan": "Danese",
    "dar": "Dargwa",
    "day": "Dayak",
    "del": "Delaware",
    "den": "Slavey",
    "dgr": "Tlicho",
    "din": "Dinka",
    "div": "Maldiviano",
    "doi": "Dogri",
    "dra": "Dravidiche (Altre)",
    "dsb": "Sorabo inferiore",
    "dua": "Duala",
    "dum": "Olandese medio (ca. 1050-1350)",
    "dut": "Olandese",
    "dyu": "Dioula",
    "dzo": "Dzongkha",
    "efi": "Efik",
    "egy": "Egizio",
    "eka": "Ekajuk",
    "elx": "Elamita",
    "eng": "Inglese",
    "enm": "Inglese medio (1100-1500)",
    "epo": "Esperanto",
    "est": "Estone",
    "ewe": "Ewe",
    "ewo": "Ewondo",
    "fan": "Fang",
    "fao": "Faringio",
    "fat": "Fanti",
    "fij": "Figiano",
    "fil": "Filippino",
    "fin": "Finlandese",
    "fiu": "Ugrofinniche (Altre)",
    "fon": "Fon",
    "fre": "Francese",
    "frm": "Francese medio (ca. 1300-1600)",
    "fro": "Francese antico (ca. 842-1300)",
    "frr": "Frisone settentrionale",
    "frs": "Frisone orientale",
    "fry": "Frisone",
    "ful": "Fula",
    "fur": "Friulano",
    "gaa": "Ga",
    "gay": "Gayo",
    "gba": "Gbaya",
    "gem": "Germaniche (Altre)",
    "geo": "Georgiano",
    "ger": "Tedesco",
    "gez": "Etiopico",
    "gil": "Gilbertese",
    "gla": "Gaelico scozzese",
    "gle": "Irlandese",
    "glg": "Galiziano",
    "glv": "Manx",
    "gmh": "Tedesco alto medio (ca. 1050-1500)",
    "goh": "Tedesco alto antico (ca. 750-1050)",
    "gon": "Gondi",
    "gor": "Gorontalo",
    "got": "Gotico",
    "grb": "Grebo",
    "grc": "Greco antico (fino al 1453)",
    "gre": "Greco moderno (1453-)",
    "grn": "Guaraní",
    "gsw": "Tedesco svizzero",
    "guj": "Gujarati",
    "gwi": "Gwich'in",
    "hai": "Haida",
    "hat": "Creolo haitiano",
    "hau": "Hausa",
    "haw": "Hawaiano",
    "heb": "Ebraico",
    "her": "Herero",
    "hil": "Hiligaynon",
    "him": "Lingue pahari occidentali",
    "hin": "Hindi",
    "hit": "Ittita",
    "hmn": "Hmong",
    "hmo": "Hiri Motu",
    "hrv": "Croato",
    "hsb": "Sorabo superiore",
    "hun": "Ungherese",
    "hup": "Hupa",
    "iba": "Iban",
    "ibo": "Igbo",
    "ice": "Islandese",
    "ido": "Ido",
   #"iii": "Sichuan Yi",
    "ijo": "Ijo",
    "iku": "Inuktitut",
    "ile": "Interlingue",
    "ilo": "Ilocano",
    "ina": "Interlingua (International Auxiliary Language Association)",
    "inc": "Indoarie (Altre)",
    "ind": "Indonesiano",
    "ine": "Indoeuropee (Altre)",
    "inh": "Inguscio",
    "ipk": "Inupiaq",
    "ira": "Iraniche (Altre)",
    "iro": "Irochesi (Altre)",
    "ita": "Italiano",
    "jav": "Giavanese",
    "jbo": "Lojban (Lingua artificiale)",
    "jpn": "Giapponese",
    "jpr": "Giudeo-persiano",
    "jrb": "Giudeo-arabo",
    "kaa": "Karakalpako",
    "kab": "Cabilo",
    "kac": "Kachin",
    "kal": "Groenlandese",
    "kam": "Kamba",
    "kan": "Kannada",
    "kar": "Lingue karen",
    "kas": "Kashmiri",
    "kau": "Kanuri",
    "kaw": "Kawi",
    "kaz": "Kazako",
    "kbd": "Cabardo",
    "kha": "Khasi",
    "khi": "Khoisan (Altre)",
    "khm": "Khmer",
    "kho": "Cotanese",
    "kik": "Kikuyu",
    "kin": "Kinyarwanda",
    "kir": "Kirghiso",
    "kmb": "Kimbundu",
    "kok": "Konkani",
    "kom": "Komi",
    "kon": "Kongo",
    "kor": "Coreano",
    "kos": "Kosraean",
    "kpe": "Kpelle",
    "krc": "Karachay-Balkar",
    "krl": "Careliano",
    "kro": "Kru (Altre)",
    "kru": "Kurukh",
    "kua": "Kuanyama",
    "kum": "Kumyk",
    "kur": "Curdo",
    "kut": "Kootenai",
    "lad": "Giudeo-spagnolo",
    "lah": "Lahnda",
    "lam": "Lamba (Zambia e Congo)",
    "lao": "Laotiano",
    "lat": "Latino",
    "lav": "Lettone",
    "lez": "Lesgo",
    "lim": "Limburghese",
    "lin": "Lingala",
    "lit": "Lituano",
    "lol": "Mongo",
    "loz": "Lozi",
    "ltz": "Lussemburghese",
    "lua": "Luba-Lulua",
    "lub": "Luba-Katanga",
    "lug": "Luganda",
    "lui": "Luiseño",
    "lun": "Lunda",
    "luo": "Luo (Kenya e Tanzania)",
    "lus": "Lushai",
    "mac": "Macedone",
    "mad": "Madurese",
    "mag": "Magahi",
    "mah": "Marshallese",
    "mai": "Maithili",
    "mak": "Makasar",
    "mal": "Malayalam",
    "man": "Mandingo",
    "mao": "Maori",
    "map": "Austronesiane (Altre)",
    "mar": "Marathi",
    "mas": "Masai",
    "may": "Malese",
    "mdf": "Moksha",
    "mdr": "Mandar",
    "men": "Mende",
    "mga": "Irlandese medio (ca. 1100-1550)",
    "mic": "Micmac",
    "min": "Minangkabau",
    "mis": "Lingue varie",
    "mkh": "Mon-Khmer (Altre)",
    "mlg": "Malgascio",
    "mlt": "Maltese",
    "mnc": "Mancese",
    "mni": "Manipuri",
    "mno": "Lingue manobo",
    "moh": "Mohawk",
    "mon": "Mongolo",
    "mos": "More",
    "mul": "Lingue multiple",
    "mun": "Munda (Altre)",
    "mus": "Creek",
    "mwl": "Mirandese",
    "mwr": "Marwari",
    "myn": "Lingue maya",
    "myv": "Erzya",
    "nah": "Nahuatl",
    "nai": "Indiane nordamericane (Altre)",
    "nap": "Napoletano",
    "nau": "Nauru",
    "nav": "Navajo",
    "nbl": "Ndebele (Sudafrica)",
    "nde": "Ndebele (Zimbabwe)",
    "ndo": "Ndonga",
    "nds": "Basso tedesco",
    "nep": "Nepalese",
    "new": "Newari",
    "nia": "Nias",
    "nic": "Niger-Kordofaniane (Altre)",
    "niu": "Niueano",
    "nno": "Norvegese (Nynorsk)",
    "nob": "Norvegese (Bokmål)",
    "nog": "Nogai",
    "non": "Antico nordico",
    "nor": "Norvegese",
    "nqo": "N'Ko",
    "nso": "Sotho del nord",
    "nub": "Lingue nubiane",
    "nwc": "Newari antico",
    "nya": "Nyanja",
    "nym": "Nyamwezi",
    "nyn": "Nyankole",
    "nyo": "Nyoro",
    "nzi": "Nzima",
    "oci": "Occitano (post-1500)",
    "oji": "Ojibwa",
    "ori": "Oriya",
    "orm": "Oromo",
    "osa": "Osage",
    "oss": "Osseto",
    "ota": "Turco ottomano",
    "oto": "Lingue otomiane",
    "paa": "Papuane (Altre)",
    "pag": "Pangasinan",
    "pal": "Pahlavi",
    "pam": "Pampanga",
    "pan": "Punjabi",
    "pap": "Papiamento",
    "pau": "Palauano",
    "peo": "Persiano antico (ca. 600-400 a.C.)",
    "per": "Persiano",
    "phi": "Filippine (Altre)",
    "phn": "Fenicio",
    "pli": "Pali",
    "pol": "Polacco",
    "pon": "Pohnpeian",
    "por": "Portoghese",
    "pra": "Lingue pracrite",
    "pro": "Provenzale (fino al 1500)",
    "pus": "Pashto",
    "que": "Quechua",
    "raj": "Rajasthani",
    "rap": "Rapanui",
    "rar": "Rarotongano",
    "roa": "Romanze (Altre)",
    "roh": "Romancio",
    "rom": "Romani",
    "rum": "Rumeno",
    "run": "Rundi",
    "rup": "Aromeno",
    "rus": "Russo",
    "sad": "Sandawe",
    "sag": "Sango",
    "sah": "Jacuto",
    "sai": "Indiane sudamericane (Altre)",
    "sal": "Lingue salish",
    "sam": "Aramaico samaritano",
    "san": "Sanscrito",
    "sas": "Sasak",
    "sat": "Santali",
    "scn": "Siciliano",
    "sco": "Scots",
    "sel": "Selcupo",
    "sem": "Semitiche (Altre)",
    "sga": "Irlandese antico (fino al 1100)",
    "sgn": "Lingue dei segni",
    "shn": "Shan",
    "sid": "Sidamo",
    "sin": "Cingalese",
    "sio": "Siouan (Altre)",
    "sit": "Sino-tibetane (Altre)",
    "sla": "Slave (Altre)",
    "slo": "Slovacco",
    "slv": "Sloveno",
    "sma": "Sami meridionale",
    "sme": "Sami settentrionale",
    "smi": "Sami",
    "smj": "Sami di Lule",
    "smn": "Sami di Inari",
    "smo": "Samoano",
    "sms": "Sami skolt",
    "sna": "Shona",
    "snd": "Sindhi",
    "snk": "Soninke",
    "sog": "Sogdiano",
    "som": "Somalo",
    "son": "Songhai",
    "sot": "Sotho",
    "spa": "Spagnolo",
    "srd": "Sardo",
    "srn": "Sranan Tongo",
    "srp": "Serbo",
    "srr": "Serer",
    "ssa": "Nilo-sahariane (Altre)",
    "ssw": "Swati",
    "suk": "Sukuma",
    "sun": "Sundanese",
    "sus": "Susu",
    "sux": "Sumero",
    "swa": "Swahili",
    "swe": "Svedese",
    "syc": "Siriaco",
    "syr": "Siriaco moderno",
    "tah": "Tahitiano",
    "tai": "Tai (Altre)",
    "tam": "Tamil",
    "tat": "Tataro",
    "tel": "Telugu",
    "tem": "Temne",
    "ter": "Terena",
    "tet": "Tetum",
    "tgk": "Tagico",
    "tgl": "Tagalog",
    "tha": "Thailandese",
    "tib": "Tibetano",
    "tig": "Tigrè",
    "tir": "Tigrino",
    "tiv": "Tiv",
    "tkl": "Tokelauano",
    "tlh": "Klingon (Lingua artificiale)",
    "tli": "Tlingit",
    "tmh": "Tamashek",
    "tog": "Tonga (Nyasa)",
    "ton": "Tongano",
    "tpi": "Tok Pisin",
    "tsi": "Tsimshian",
    "tsn": "Tswana",
    "tso": "Tsonga",
    "tuk": "Turcomanno",
    "tum": "Tumbuka",
    "tup": "Lingue tupi",
    "tur": "Turco",
    "tut": "Altaiche (Altre)",
    "tvl": "Tuvaluano",
    "twi": "Twi",
    "tyv": "Tuvano",
    "udm": "Udmurto",
    "uga": "Ugaritico",
    "uig": "Uiguro",
    "ukr": "Ucraino",
    "umb": "Umbundu",
    "und": "Indeterminato",
    "urd": "Urdu",
    "uzb": "Uzbeco",
    "vai": "Vai",
    "ven": "Venda",
    "vie": "Vietnamita",
    "vol": "Volapük",
    "vot": "Votico",
    "wak": "Lingue wakashan",
    "wal": "Wolayta",
    "war": "Waray",
    "was": "Washoe",
    "wel": "Gallese",
    "wen": "Sorabe (Altre)",
    "wln": "Vallone",
    "wol": "Wolof",
    "xal": "Calmucco",
    "xho": "Xhosa",
    "yao": "Yao (Africa)",
    "yap": "Yapese",
    "yid": "Yiddish",
    "yor": "Yoruba",
    "ypk": "Lingue yupik",
    "zap": "Zapoteco",
    "zbl": "Simboli Bliss",
    "zen": "Zenaga",
    "zha": "Zhuang",
    "znd": "Lingue zande",
    "zul": "Zulu",
    "zun": "Zuni",
    "zxx": "Nessun contenuto linguistico",
    "zza": "Zaza"
}