const relationshipMappings = {
    "WORK": [
        {"name": "work_has_uniform_title", "label": "Uniform title"},
        {"name": "work_has_classification", "label": "Classification"},
        {"name": "work_authored_by", "label": "Author"},
        {"name": "work_is_mentioning", "label": "Mentioning"},
        {"name": "work_is_mentioned_by", "label": "Mentioned by"},
        {"name": "work_has_hypothesis", "label": "Hypothesis"}
    ],
    "EXPRESSION": [
        {"name": "expression_has_medium", "label": "Medium"},
        {"name": "expression_has_language", "label": "Language"},
        {"name": "expression_has_number", "label": "Number"},
        {"name": "expression_has_type", "label": "Type"},
        {"name": "expression_has_completeness", "label": "Completeness"},
        {"name": "expression_has_incipit", "label": "Incipit"},
        {"name": "expression_has_explicit", "label": "Explicit"},
        {"name": "is_expression_of_work", "label": "Work expressed"},
        {"name": "expression_has_secondary_author", "label": "Secondary author"},
        {"name": "expression_has_responsibility_statement", "label": "Responsibility statement"},
        {"name": "expression_is_mentioning", "label": "Mentioning"},
        {"name": "expression_is_mentioned_by", "label": "Mentioned by"},
        {"name": "expression_has_hypothesis", "label": "Hypothesis"}
    ],
    "MANIFESTATION": [
        {"name": "manifestation_has_volume", "label": "Volume"},
        {"name": "manifestation_has_external_id", "label": "External ID"},
        {"name": "manifestation_has_short_title", "label": "Short title"},
        {"name": "manifestation_published_in_place", "label": "Place of publication"},
        {"name": "manifestation_has_publication_date", "label": "Date of publication"},
        {"name": "manifestation_has_print_run", "label": "Print run"},
        {"name": "manifestation_has_edition_number", "label": "Edition number"},
        {"name": "manifestation_has_volume_title", "label": "Title of the volume(s)"},
        {"name": "manifestation_has_number_of_volumes", "label": "Number of volumes"},
        {"name": "manifestation_has_publication_date_range", "label": "Date range of publication"},
        {"name": "manifestation_has_format", "label": "Format"},
        {"name": "manifestation_has_collation_formula", "label": "Collation formula"},
        {"name": "manifestation_has_number_of_pages", "label": "Number of pages"},
        {"name": "manifestation_has_introduction_pages", "label": "Introduction pages"},
        {"name": "manifestation_has_external_digitization", "label": "External digitization"},
        {"name": "manifestation_has_pages", "label": "Pages"},
        {"name": "is_manifestation_of_expression", "label": "Expression manifested"},
        {"name": "manifestation_published_by", "label": "Publisher"},
        {"name": "manifestation_edited_by", "label": "Editor"},
        {"name": "manifestation_corrected_by", "label": "Corrector"},
        {"name": "manifestation_sponsored_by", "label": "Sponsor"},
        {"name": "manifestation_is_mentioning", "label": "Mentioning"},
        {"name": "manifestation_is_mentioned_by", "label": "Mentioned by"},
        {"name": "manifestation_has_hypothesis", "label": "Hypothesis"}
    ],
    "MANIFESTATION_VOLUME": [
        {"name": "manifestation_volume_has_external_id", "label": "External ID"},
        {"name": "manifestation_volume_has_short_title", "label": "Short title"},
        {"name": "manifestation_volume_published_in_place", "label": "Place of publication"},
        {"name": "manifestation_volume_has_publication_date", "label": "Date of publication"},
        {"name": "manifestation_volume_has_print_run", "label": "Print run"},
        {"name": "manifestation_volume_has_edition_number", "label": "Edition number"},
        {"name": "manifestation_volume_has_volume_title", "label": "Title of the volume(s)"},
        {"name": "manifestation_volume_has_number_of_volumes", "label": "Number of volumes"},
        {"name": "manifestation_volume_has_publication_date_range", "label": "Date range of publication"},
        {"name": "manifestation_volume_has_format", "label": "Format"},
        {"name": "manifestation_volume_has_collation_formula", "label": "Collation formula"},
        {"name": "manifestation_volume_has_number_of_pages", "label": "Number of pages"},
        {"name": "manifestation_volume_has_introduction_pages", "label": "Introduction pages"},
        {"name": "manifestation_volume_has_external_digitization", "label": "External digitization"},
        {"name": "manifestation_volume_has_pages", "label": "Pages"},
        {"name": "is_manifestation_volume_of_expression", "label": "Expression manifested"},
        {"name": "manifestation_volume_published_by", "label": "Publisher"},
        {"name": "manifestation_volume_edited_by", "label": "Editor"},
        {"name": "manifestation_volume_corrected_by", "label": "Corrector"},
        {"name": "manifestation_volume_sponsored_by", "label": "Sponsor"},
        {"name": "manifestation_volume_is_mentioning", "label": "Mentioning"},
        {"name": "manifestation_volume_is_mentioned_by", "label": "Mentioned by"}
    ],
    
    "PLACE": [
        {"name": "place_has_name", "label": "Name"},
        {"name": "place_has_description", "label": "Description (Wikidata)"},
        {"name": "place_has_wikidata_link", "label": "Wikidata link"},
        {"name": "place_has_alias", "label": "Also known as"},
        {"name": "place_has_viaf_code", "label": "VIAF code"},
        {"name": "place_has_other_codes", "label": "Other codes"},
        {"name": "place_has_wikidata_id", "label": "Wikidata ID"},
        {"name": "place_has_coordinates", "label": "Coordinates"},
        {"name": "place_is_mentioning", "label": "Mentioning"},
        {"name": "place_mentioned_by", "label": "Mentioned by"},
        {"name": "place_has_hypothesis", "label": "Hypothesis"}
    ],
    "ITEM": [
        {"name": "item_has_shelf_mark", "label": "Shelf mark"},
        {"name": "item_has_preservation_status", "label": "Preservation status"},
        {"name": "item_has_material", "label": "Material"},
        {"name": "item_has_type", "label": "Type"},
        {"name": "item_has_dimensions", "label": "Dimensions (height/width)"},
        {"name": "item_has_copy_number", "label": "Copy number"},
        {"name": "item_has_surviving_pages", "label": "Surviving pages"},
        {"name": "item_has_page_preservation_status", "label": "Page preservation status"},
        {"name": "item_has_physical_description", "label": "Physical description"},
        {"name": "item_owned_by", "label": "Owner"},
        {"name": "item_contains_physical_object", "label": "Contains physical object"},
        {"name": "is_item_of_manifestation", "label": "Manifestation item"},
        {"name": "item_is_mentioning", "label": "Mentioning"},
        {"name": "item_mentioned_by", "label": "Mentioned by"},
        {"name": "item_has_hypothesis", "label": "Hypothesis"}
    ],
    "PAGE": [
        {"name": "item_has_page", "label": "Page of item"},
        {"name": "page_has_name", "label": "Name"},
        {"name": "page_has_description", "label": "Description"},
        {"name": "page_has_material", "label": "Material"},
        {"name": "page_has_digital_representation", "label": "Digital representation"},
        {"name": "page_references_physical_object", "label": "References physical object"},
        {"name": "page_contains_visual_object", "label": "Contains visual object"},
        {"name": "page_contains_physical_object", "label": "Contains physical object"},
        {"name": "page_contains_physical_object_page", "label": "Contains physical object page"},    
        {"name": "page_is_mentioning", "label": "Mentioning"},
        {"name": "page_mentioned_by", "label": "Mentioned by"},
        {"name": "page_has_hypothesis", "label": "Hypothesis"}
    ],
    "VISUAL_OBJECT": [
        {"name": "visual_object_has_instrument", "label": "Instrument"},
        {"name": "visual_object_has_colour", "label": "Colour"},
        {"name": "visual_object_has_type", "label": "Type"},
        {"name": "visual_object_has_transcription", "label": "Transcription"},
        {"name": "visual_object_has_description", "label": "Description"},
        {"name": "visual_object_has_transcription_quality", "label": "Transcription quality"},
        {"name": "visual_object_has_function", "label": "Function"},
        {"name": "visual_object_has_language", "label": "Language"},
        {"name": "visual_object_has_position_on_page", "label": "Position on page"},
        {"name": "visual_object_located_at_place", "label": "Place"},
        {"name": "visual_object_has_date", "label": "Date"},
        {"name": "visual_object_owned_by", "label": "Owner"},
        {"name": "visual_object_inscribed_by", "label": "Inscribed by"},
        {"name": "visual_object_sent_by", "label": "Sent by"},
        {"name": "visual_object_received_by", "label": "Received by"},
        {"name": "visual_object_is_mentioning", "label": "Mentioning"},
        {"name": "visual_object_is_mentioned_by", "label": "Mentioned by"},
        {"name": "visual_object_has_hypothesis", "label": "Hypothesis"}
    ],
    "PERSON": [
        {"name": "person_has_name", "label": "Name"},
        {"name": "person_has_birth_date", "label": "Date of birth"},
        {"name": "person_has_birth_date_notes", "label": "Birth date notes"},
        {"name": "person_has_death_date", "label": "Date of death"},
        {"name": "person_has_death_date_notes", "label": "Death date notes"},
        {"name": "person_has_notes", "label": "Additional notes"},
        {"name": "person_has_wikidata_link", "label": "Wikidata link"},
        {"name": "person_has_gender", "label": "Gender"},
        {"name": "person_has_alias", "label": "Also known as"},
        {"name": "person_member_of_institution", "label": "Member of institution"},
        {"name": "person_has_description", "label": "Description (Wikidata)"},
        {"name": "person_has_viaf_code", "label": "VIAF code"},
        {"name": "person_has_other_codes", "label": "Other codes"},
        {"name": "person_has_wikidata_id", "label": "Wikidata ID"},
        {"name": "person_is_mentioning", "label": "Mentioning"},
        {"name": "person_is_mentioned_by", "label": "Mentioned by"},
        {"name": "person_has_hypothesis", "label": "Hypothesis"}
    ],
    "PHYSICAL_OBJECT": [
        {"name": "physical_object_has_insertion_type", "label": "Insertion type"},
        {"name": "physical_object_has_type", "label": "Type"},
        {"name": "physical_object_has_description", "label": "Description"},
        {"name": "physical_object_has_dimensions", "label": "Dimensions (height/width)"},
        {"name": "physical_object_has_preservation_status", "label": "Preservation status"},
        {"name": "physical_object_located_at_place", "label": "Place"},
        {"name": "physical_object_has_date", "label": "Date"},
        {"name": "physical_object_created_by", "label": "Created by"},
        {"name": "physical_object_owned_by", "label": "Owned by"},
        {"name": "physical_object_is_mentioning", "label": "Mentioning"},
        {"name": "abstract_character_mentioned_by", "label": "Mentioned by"},
        {"name": "physical_object_has_hypothesis", "label": "Hypothesis"}
    ],
    "EVENT": [
        {"name": "event_has_name", "label": "Name"},
        {"name": "event_has_description", "label": "Description"},
        {"name": "event_has_wikidata_link", "label": "Wikidata link"},
        {"name": "event_has_date", "label": "Date"},
        {"name": "event_occurred_at_place", "label": "Place"},
        {"name": "event_has_wikidata_description", "label": "Description (Wikidata)"},
        {"name": "event_has_alias", "label": "Also known as"},
        {"name": "event_has_viaf_code", "label": "VIAF code"},
        {"name": "event_has_other_codes", "label": "Other codes"},
        {"name": "event_has_wikidata_id", "label": "Wikidata ID"},
        {"name": "event_is_mentioning", "label": "Mentioning"},
        {"name": "abstract_character_mentioned_by", "label": "Mentioned by"},
        {"name": "event_has_hypothesis", "label": "Hypothesis"}
    ],
    "ABSTRACT_CHARACTER": [
        {"name": "abstract_character_has_name", "label": "Name"},
        {"name": "abstract_character_has_type", "label": "Type"},
        {"name": "abstract_character_has_gender", "label": "Gender"},
        {"name": "abstract_character_has_description", "label": "Description"},
        {"name": "abstract_character_has_wikidata_link", "label": "Wikidata link"},
        {"name": "abstract_character_has_alias", "label": "Also known as"},
        {"name": "abstract_character_has_wikidata_description", "label": "Description (Wikidata)"},
        {"name": "abstract_character_has_viaf_code", "label": "VIAF code"},
        {"name": "abstract_character_has_other_codes", "label": "Other codes"},
        {"name": "abstract_character_has_wikidata_id", "label": "Wikidata ID"},
        {"name": "abstract_character_is_mentioning", "label": "Mentioning"},
        {"name": "abstract_character_mentioned_by", "label": "Mentioned by"},
        {"name": "abstract_character_has_hypothesis", "label": "Hypothesis"}
    ],
    "INSTITUTION": [
        {"name": "institution_has_name", "label": "Name"},
        {"name": "institution_has_wikidata_link", "label": "Wikidata link"},
        {"name": "institution_has_founding_date", "label": "Founding date"},
        {"name": "institution_has_dissolution_date", "label": "Dissolution date"},
        {"name": "institution_located_at_place", "label": "Place"},
        {"name": "institution_has_founding_date_notes", "label": "Founding date notes"},
        {"name": "institution_has_dissolution_date_notes", "label": "Dissolution date notes"},
        {"name": "institution_has_wikidata_description", "label": "Description (Wikidata)"},
        {"name": "institution_has_alias", "label": "Also known as"},
        {"name": "institution_has_viaf_code", "label": "VIAF code"},
        {"name": "institution_has_other_codes", "label": "Other codes"},
        {"name": "institution_has_wikidata_id", "label": "Wikidata ID"},
        {"name": "institution_is_mentioning", "label": "Mentioning"},
        {"name": "institution_is_mentioned_by", "label": "Mentioned by"},
        {"name": "institution_has_hypothesis", "label": "Hypothesis"}
    ],
    "HYPOTHESIS": [
        {"name": "hypothesis_has_description", "label": "Description"},
        {"name": "hypothesis_has_date", "label": "Date"},
        {"name": "hypothesis_created_by_person", "label": "Created by (person)"},
        {"name": "is_hypothesis_about", "label": "About entity/entities"}
    ]
}